services:
  backend:
    ports:
      - "8000:8000"
    user: "1000:1000"
    volumes:
      - ./backend:/backend
      - ./requirements:/requirements
      - ./scripts:/scripts

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
